### ISSUE TITLE
electric-delimiters: [binding error] index not at rune boundary

### ISSUE THREAD

**Issue by SitiSchu** [zzamboni/elvish-modules#11]
Steps to reproduce:
```
~> use github.com/zzamboni/elvish-modules/util
~> util:electric-delimiters
```
- Type a non-ASCII character (for example: `öäü`)
- Press backspace and the following error is caused:

```
[binding error] index not at rune boundary
```

**Comment by zzamboni** [comment]
@SitiSchu fixed - thanks for reporting!

@xiaq I'm not super happy with [my fix](https://github.com/zzamboni/elvish-modules/commit/3ff9fe88bb40dff3591d7e40e3c7dfa06c584e60#diff-ee619dda14f3c28e964ff37570e0b5b5R146-R147), is there some better way to get the "rune to the left" without doing this looping?
