### ISSUE TITLE
[dir] Error messages: option to disable / customize output

### ISSUE THREAD

**Issue by tfga** [zzamboni/elvish-modules#12]
The error messages (e.g. "Beginning/End of directory history!") are messing with my prompt. I have to press `Enter` or run `clear` to have it restored. Would it be possible to implement some mechanism to disable them or customize where/how they will be printed? E.g. I was thinking about showing them in the rprompt.

An idea: have some variable, say `dir:print-error`, whose default value would be the current behaviour:
```
print-error = [msg]{

    echo $msg > /dev/tty
}
```
and then functions like e.g. `back` would use it:
```
fn back {
  if (> $-cursor 0) {
    -cursor = (- $-cursor 1)
    builtin:cd $-dirstack[$-cursor]
  } else {
    $print-error "Beginning of directory history!"   # <= here
  }
}
```
Then I would be able to override `dir:print-error` in my `rc.elv` to implement the behaviour that I want.

**Comment by tfga** [comment]
PS: @zzamboni Great work, BTW! Thanks a lot! :+1:

**Comment by zzamboni** [comment]
@tfga thanks for the idea and the kind words! Fixed.

**Comment by tfga** [comment]
Updated and using. :smile: 
Thanks! :ok_hand: :+1:
