### ISSUE TITLE
util:getfile no longer works correctly

### ISSUE THREAD

**Issue by hanche** [zzamboni/elvish-modules#13]
At some point, Apple in their infinite wisdom has changed the escape conventions for filenames dragged from the Finder into the terminal, so the current code no longer works.

This seems to be the new convention:

- If the dragged pathname is free of special characters, it is input as is. So far so good.
- If there are special characters, the pathname is quoted using single quotes. If so,
  - single quotes in the path name are escaped with a preceding backslash,
  - and so is any backslash.

Example: A file named `a'b\c` gets entered as `'…/a\'b\\c'`, where `…` is the directory part.

I don't know of any shell that obeys these escape conventions – certainly not `bash` or `zsh` – so I don't know what Apple has been thinking. And since these seem so awfully wrong, I suspect it may get changed yet again. If not, the new convention is easy enough to parse, but I don't have a moment to spare for this in the foreseeable future.

**Comment by zzamboni** [comment]
@hanche I think I've fixed this, but since I don't use `util:getfile` too much myself, could you please test?

**Comment by hanche** [comment]
It appears to work correctly.
(Sorry to be late in responding; I've been on vacation.)
