### ISSUE TITLE
error loading modules

### ISSUE THREAD

**Issue by jacostag** [zzamboni/elvish-modules#15]
Hello, I just discovered elvish, and I am loving it.
I can use:
use github.com/iwoloschin/elvish-packages/update
use epm
  epm:install &silent-if-installed         ^
  github.com/zzamboni/elvish-modules     ^
  github.com/zzamboni/elvish-completions ^
  github.com/zzamboni/elvish-themes      ^
  github.com/xiaq/edit.elv               ^
  github.com/muesli/elvish-libs          ^

without issues

But, I am trying to use bang-bang or aliases and is failing
use github.com/zzamboni/elvish-completions/alias
Exception: no such module: github.com/zzamboni/elvish-completions/alias
[tty 46], line 1: use github.com/zzamboni/elvish-completions/alias

Any idea of what am I doing wrong?

Thanks

**Comment by zzamboni** [comment]
@jacostag glad you like Elvish!

The error is because you are loading the wrong path. It should be `github.com/zzamboni/elvish-modules/alias` instead of `github.com/zzamboni/elvish-completions/alias`.

**Comment by jacostag** [comment]
hello, again, sorry, but is still not working for me :/
Exception: no such module: github.com/zzamboni/elvish-modules/alias
/home/gosz/.elvish/rc.elv, line 32: use github.com/zzamboni/elvish-modules/alias

This is my rc.elv:

eval (starship init elvish)
#eval $(thefuck --alias)
#eval "$(zoxide init bash)"

fn ls [@a]{ e:lsd $@a }
fn br [@arguments]{ #does not work
  broot:br $@arguments
}
fn cat [@_args]{ bat $@_args }

use readline-binding

edit:insert:binding[Alt-Backspace] = $edit:kill-small-word-left~
edit:insert:binding[Alt-m] = $edit:-instant:start~
edit:max-height = 30

E:MANPAGER = "sh -c 'col -bx | bat -l man -p'"
E:EDITOR = "vim"
E:LC_ALL = "en_US.UTF-8"


use epm

epm:install &silent-if-installed         ^
  github.com/zzamboni/elvish-modules     ^
  github.com/zzamboni/elvish-completions ^
  github.com/zzamboni/elvish-themes      ^
  github.com/xiaq/edit.elv               ^
  github.com/muesli/elvish-libs          ^
  github.com/iwoloschin/elvish-packages

use github.com/zzamboni/elvish-modules/alias #nor working

use github.com/zzamboni/elvish-modules/bang-bang #not working

use github.com/iwoloschin/elvish-packages/update
update:curl-timeout = 3
update:check-commit &verbose

**Comment by zzamboni** [comment]
Can you run the following command by hand:
```
epm:install github.com/zzamboni/elvish-modules
```
And then try to load the module again:
```
use github.com/zzamboni/elvish-modules/alias
```
If it still doesn't work, please check the following:
- Does `~/.elvish/lib/github.com/zzamboni/elvish-modules/` exist? (if so, remove it and try again)
- What errors do you get in the commands above?

**Comment by jacostag** [comment]
❯ epm:install github.com/zzamboni/elvish-modules
=> Package github.com/zzamboni/elvish-modules is already installed.
                                                                                                                                                                                               
~ via 💎 v2.7.1
❯ use github.com/zzamboni/elvish-modules/alias
Exception: no such module: github.com/zzamboni/elvish-modules/alias
[tty 2], line 1: use github.com/zzamboni/elvish-modules/alias
                                                                                                                                                                                               
~ via 💎 v2.7.1 
❯ ls ~/.elvish/lib/github.com/zzamboni/elvish-modules/
 bang-bang
                                                                                                                                                                                               
~ via 💎 v2.7.1 
❯ use github.com/zzamboni/elvish-modules/bang-bang
Exception: no such module: github.com/zzamboni/elvish-modules/bang-bang
[tty 4], line 1: use github.com/zzamboni/elvish-modules/bang-bang
                                                                                                                                                                                               
~ via 💎 v2.7.1
❯

**Comment by jacostag** [comment]
ok, I fix it.
I uninstall the modules, reinstall and start using without issues :)

Thanks for the help
