### ISSUE TITLE
Update for V0.17

### ISSUE THREAD

**Issue by iandol** [zzamboni/elvish-modules#23]
V0.17 makes some syntax changes and there are many deprecation warnings currently visible. See the upgrader script: https://github.com/elves/upgrade-scripts-for-0.17

**Comment by zzamboni** [comment]
Thanks for the report. I'm working on this and will publish a branch with the fixes for testing before merging into the main branch.

**Comment by xiaq** [comment]
Please LMK if https://go.elv.sh/u0.17 doesn't fix everything for you.

I used it in my local copy (with `upgrade-scripts-for-0.17 -w -lambda *.elv`) and everything is working, but I don't use every module from this repo.

**Comment by zzamboni** [comment]
@iandol this is fixed in the latest commit.

@xiaq the script works great - so far it seems to handle everything OK.

**Comment by iandol** [comment]
@zzamboni — can confirm everything working great, thank you!!!
