### ISSUE TITLE
`edit:insert:binding[Alt-b] = $dir:&left-word-or-prev-dir` causes error message "Exception: value should be function" regarding `$dir`

### ISSUE THREAD

**Issue by HotFusionMan** [zzamboni/elvish-modules#4]
In Elvish 0.12 on macOS Sierra 10.13.6, I added the following to ~/.elvish/rc.elv per the `dir.org` file:
```
use github.com/zzamboni/elvish-modules/dir
edit:insert:binding[Alt-b] = $dir:&left-word-or-prev-dir
edit:insert:binding[Alt-f] = $dir:&right-word-or-next-dir
edit:insert:binding[Alt-i] = $dir:&dir-chooser
```
which upon restarting Elvish generates the following error message:
```
Exception: value should be function
/Users/alchou/.elvish/rc.elv, line 18: edit:insert:binding[Alt-b] = $dir:&left-word-or-prev-dir
```
wherein the substring `$dir:` is underlined.

**Comment by zzamboni** [comment]
Thanks, good catch. The examples were still using the old function-reference syntax `$&foo` instead of `$foo~`. Also, `dir-chooser` has been renamed to `history-chooser`. I've fixed both.
