### ISSUE TITLE
alias.org README should say to place `-exports- = (alias:export)` after all `alias:new` lines

### ISSUE THREAD

**Issue by HotFusionMan** [zzamboni/elvish-modules#5]
I couldn't get `alias:new cd "use github.com/zzamboni/elvish-modules/dir; dir:cd"` to work until I made sure the line `-exports- = (alias:export)` appeared in rc.elv after it.

**Comment by zzamboni** [comment]
This is mentioned near the top of the [Usage](https://github.com/zzamboni/elvish-modules/blob/master/alias.org#usage) section in [alias.org](https://github.com/zzamboni/elvish-modules/blob/master/alias.org#usage):

> In your rc.elv, load this module and assign the output of alias:export to the $-exports- variable to make existing aliases available as top-level commands:
> 
>     use github.com/zzamboni/elvish-modules/alias
>     -exports- = (alias:export)
